#!/usr/bin/python3

import sys

from sympy import *

x = Symbol('x')
y = Symbol('y')

exps = []
with open(sys.argv[1], 'r') as f:
    for exp in f:
        if exp.startswith("#"):
            continue
        if exp == '\n':
            continue
        exp = exp.strip()
        exp = exp.replace(" ", "")
        exp = exp.replace("=-", "+")
        exp = exp.replace("=", "-")
        exps.append(exp)
result = solve(exps, [x, y])
print(result)
